/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair.gltf --transform
Author: Outworld Studios (https://sketchfab.com/outworldstudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dune-ornithopter-9d7e8fd437c44c1c956e5935d826ab86
Title: Dune Ornithopter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Orni_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Orni_Material001_0.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Orni1_Material003_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
